server:
  port: 8081
spring:
  application:
    name: eureka
  cloud:
    config:
      allow-override: false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/